VehicleMods = {
    mods = {
        engine = {
            label = "Engine",
            typeId = 11,
            reduce = 1,
        },
        brakes = {
            label = "Brakes",
            typeId = 12,
        },
        transmission = {
            label = "Transmission",
            typeId = 13,
        },
        suspension = {
            label = "Suspension",
            typeId = 15,
        },
        armor = {
            label = "Armour",
            typeId = 16,
        },
        turbo = {
            label = "Turbo",
            typeId = 18,
            toggle = true,
        },
    },
    colours = {
        chrome = {
            { name = "Chrome", index = 120 },
        },
        classic = {
            { name = "Black", index = 0 },
            { name = "Carbon Black", index = 147 },
            { name = "Hraphite", index = 1 },
            { name = "Anhracite Black", index = 11 },
            { name = "Black Steel", index = 2 },
            { name = "Dark Steel", index = 3 },
            { name = "Silver", index = 4 },
            { name = "Bluish Silver", index = 5 },
            { name = "Rolled Steel", index = 6 },
            { name = "Shadow Silver", index = 7 },
            { name = "Stone Silver", index = 8 },
            { name = "Midnight Silver", index = 9 },
            { name = "Cast Iron Silver", index = 10 },
            { name = "Red", index = 27 },
            { name = "Torino Red", index = 28 },
            { name = "Formula Red", index = 29 },
            { name = "Lava Red", index = 150 },
            { name = "Blaze Red", index = 30 },
            { name = "Grace Red", index = 31 },
            { name = "Garnet Red", index = 32 },
            { name = "Sunset Red", index = 33 },
            { name = "Cabernet Red", index = 34 },
            { name = "Wine Red", index = 143 },
            { name = "Candy Red", index = 35 },
            { name = "Hot Pink", index = 135 },
            { name = "Pfsiter Pink", index = 137 },
            { name = "Salmon Pink", index = 136 },
            { name = "Sunrise Orange", index = 36 },
            { name = "Orange", index = 38 },
            { name = "Bright Orange", index = 138 },
            { name = "Gold", index = 99 },
            { name = "Bronze", index = 90 },
            { name = "Yellow", index = 88 },
            { name = "Race Yellow", index = 89 },
            { name = "Dew Yellow", index = 91 },
            { name = "Dark Green", index = 49 },
            { name = "Racing Green", index = 50 },
            { name = "Sea Green", index = 51 },
            { name = "Olive Green", index = 52 },
            { name = "Bright Green", index = 53 },
            { name = "Gasoline Green", index = 54 },
            { name = "Lime Green", index = 92 },
            { name = "Midnight Blue", index = 141 },
            { name = "Galaxy Blue", index = 61 },
            { name = "Dark Blue", index = 62 },
            { name = "Saxon Blue", index = 63 },
            { name = "Blue", index = 64 },
            { name = "Mariner Blue", index = 65 },
            { name = "Harbor Blue", index = 66 },
            { name = "Diamond Blue", index = 67 },
            { name = "Surf Blue", index = 68 },
            { name = "Nautical Blue", index = 69 },
            { name = "Racing Blue", index = 73 },
            { name = "Ultra Blue", index = 70 },
            { name = "Light Blue", index = 74 },
            { name = "Chocolate Brown", index = 96 },
            { name = "Bison Brown", index = 101 },
            { name = "Creeen Brown", index = 95 },
            { name = "Feltzer Brown", index = 94 },
            { name = "Maple Brown", index = 97 },
            { name = "Beechwood Brown", index = 103 },
            { name = "Sienna Brown", index = 104 },
            { name = "Saddle Brown", index = 98 },
            { name = "Moss Brown", index = 100 },
            { name = "Woodbeech Brown", index = 102 },
            { name = "Straw Brown", index = 99 },
            { name = "Sandy Brown", index = 105 },
            { name = "Bleached Brown", index = 106 },
            { name = "Schafter Purple", index = 71 },
            { name = "Spinnaker Purple", index = 72 },
            { name = "Midnight Purple", index = 142 },
            { name = "Bright Purple", index = 145 },
            { name = "Cream", index = 107 },
            { name = "Ice White", index = 111 },
            { name = "Frost White", index = 112 },
        },
        metal = {
            { name = "Brushed Steel", index = 117 },
            { name = "Brushed Black Steel", index = 118 },
            { name = "Brushed Aluminum", index = 119 },
            { name = "Pure Gold", index = 158 },
            { name = "Brushed Gold", index = 159 },
        },
        matte = {
            { name = "Black", index = 12 },
            { name = "Gray", index = 13 },
            { name = "Light Gray", index = 14 },
            { name = "Ice White", index = 131 },
            { name = "Blue", index = 83 },
            { name = "Dark Blue", index = 82 },
            { name = "Midnight Blue", index = 84 },
            { name = "Midnight Purple", index = 149 },
            { name = "Schafter Purple", index = 148 },
            { name = "Red", index = 39 },
            { name = "Dark Red", index = 40 },
            { name = "Orange", index = 41 },
            { name = "Yellow", index = 42 },
            { name = "Lime Green", index = 55 },
            { name = "Green", index = 128 },
            { name = "Frost Green", index = 151 },
            { name = "Foliage Green", index = 155 },
            { name = "Olive Darb", index = 152 },
            { name = "Dark Earth", index = 153 },
            { name = "Desert Tan", index = 154 },
        },
    },
    windowTint = {
        { name = "Pure Black", index = 1 },
        { name = "Darksmoke", index = 2 },
        { name = "Lightsmoke", index = 3 },
        { name = "Limo", index = 4 },
        { name = "Green", index = 5 },
    },
    plates = {
        { name = "Blue on White 1", index = 0 },
        { name = "Blue On White 2", index = 3 },
        { name = "Blue On White 3", index = 4 },
        { name = "Yellow on Blue", index = 2 },
        { name = "Yellow on Black", index = 1 },
    },
    tyreSmoke = {
        { name = "White Tire Smoke", smokecolor = { 254, 254, 254 } },
        { name = "Black Tire Smoke", smokecolor = { 1, 1, 1 } },
        { name = "Blue Tire Smoke", smokecolor = { 0, 150, 255 } },
        { name = "Yellow Tire Smoke", smokecolor = { 255, 255, 50 } },
        { name = "Orange Tire Smoke", smokecolor = { 255, 153, 51 } },
        { name = "Red Tire Smoke", smokecolor = { 255, 10, 10 } },
        { name = "Green Tire Smoke", smokecolor = { 10, 255, 10 } },
        { name = "Purple Tire Smoke", smokecolor = { 153, 10, 153 } },
        { name = "Pink Tire Smoke", smokecolor = { 255, 102, 178 } },
        { name = "Gray Tire Smoke", smokecolor = { 128, 128, 128 } },
    },
    wheels = {
        bikes = {
            index = 6,
            options = {
                { name = "Stock", index = -1 },
                { name = "Speedway", index = 0 },
                { name = "Streetspecial", index = 1 },
                { name = "Racer", index = 2 },
                { name = "Trackstar", index = 3 },
                { name = "Overlord", index = 4 },
                { name = "Trident", index = 5 },
                { name = "Triplethreat", index = 6 },
                { name = "Stilleto", index = 7 },
                { name = "Wires", index = 8 },
                { name = "Bobber", index = 9 },
                { name = "Solidus", index = 10 },
                { name = "Iceshield", index = 11 },
                { name = "Loops", index = 12 },
            },
        },
        cars = {
            sports = {
                index = 0,
                options = {
                    { name = "Stock", mod = -1 },
                    { name = "Inferno", mod = 0 },
                    { name = "Deepfive", mod = 1 },
                    { name = "Lozspeed", mod = 2 },
                    { name = "Diamondcut", mod = 3 },
                    { name = "Chrono", mod = 4 },
                    { name = "Feroccirr", mod = 5 },
                    { name = "Fiftynine", mod = 6 },
                    { name = "Mercie", mod = 7 },
                    { name = "Syntheticz", mod = 8 },
                    { name = "Organictyped", mod = 9 },
                    { name = "Endov1", mod = 10 },
                    { name = "Duper7", mod = 11 },
                    { name = "Uzer", mod = 12 },
                    { name = "Groundride", mod = 13 },
                    { name = "Spacer", mod = 14 },
                    { name = "Venum", mod = 15 },
                    { name = "Cosmo", mod = 16 },
                    { name = "Dashvip", mod = 17 },
                    { name = "Icekid", mod = 18 },
                    { name = "Ruffeld", mod = 19 },
                    { name = "Wangenmaster", mod = 20 },
                    { name = "Superfive", mod = 21 },
                    { name = "Endov2", mod = 22 },
                    { name = "Slitsix", mod = 23 },
                },
            },
            suv = {
                index = 3,
                options = {
                    { name = "Stock", mod = -1 },
                    { name = "Vip", mod = 0 },
                    { name = "Benefactor", mod = 1 },
                    { name = "Cosmo", mod = 2 },
                    { name = "Bippu", mod = 3 },
                    { name = "Royalsix", mod = 4 },
                    { name = "Fagorme", mod = 5 },
                    { name = "Deluxe", mod = 6 },
                    { name = "Icedout", mod = 7 },
                    { name = "Cognscenti", mod = 8 },
                    { name = "Lozspeedten", mod = 9 },
                    { name = "Supernova", mod = 10 },
                    { name = "Obeyrs", mod = 11 },
                    { name = "Lozspeedballer", mod = 12 },
                    { name = "Extra vaganzo", mod = 13 },
                    { name = "Splitsix", mod = 14 },
                    { name = "Empowered", mod = 15 },
                    { name = "Sunrise", mod = 16 },
                    { name = "Dashvip", mod = 17 },
                    { name = "Cutter", mod = 18 },
                },
            },
            offRoad = {
                index = 4,
                options = {
                    { name = "Stock", mod = -1 },
                    { name = "Raider", mod = 0 },
                    { name = "Mudslinger", mod = 1 },
                    { name = "Nevis", mod = 2 },
                    { name = "Cairngorm", mod = 3 },
                    { name = "Amazon", mod = 4 },
                    { name = "Challenger", mod = 5 },
                    { name = "Dunebasher", mod = 6 },
                    { name = "Fivestar", mod = 7 },
                    { name = "Rockcrawler", mod = 8 },
                    { name = "Milspecsteelie", mod = 9 },
                },
            },
        },
    },
}